### ISSUE TITLE
selectable V D and J gene

### ISSUE THREAD

**Issue by arvedh** [mikessh/migmap#24]
Hi Mike,
I really appreciate your Program. By showing the mutations and the number of deleted nucleotides it does exactly what I need. There is only one Problem. If Sequences are highly mutated the classification of the V, D and J gets more inaccurate. So that two Sequences which differ in only very few bases are classified as different V’s(or D’s or J’s), even if I know that those Sequences should have the same V.
So my Question is, would it be possible to analyze fastq files with a determined V D and J for all Sequences?
thanks a lot
Arved

here is an example of my problem:
![example](https://cloud.githubusercontent.com/assets/16323062/11844852/306bf19e-a411-11e5-82a8-16e816eda57f.png)

**Comment by mikessh** [comment]
Hello!

Indeed with high mutation/error rate those transitions are inevitable for similar J segments especially when the J segment is only partially read. However I believe that the problem lies more in the field of post-processing, namely building antibody evolution trees. In general cases, such cases should be corrected by an algorithm that traverses through the graph and tries to resolve ambiguous cases using parsimony arguments.

Currently there is no easy way to add/modify references using command line.
But you can clone the repository, modify the following file: 
https://github.com/mikessh/migmap/blob/master/src/main/resources/segments.txt
to contain only certain segments and compile the software from source.

I'll add this feature (ability to specify a custom references file) to next release.
